### ISSUE TITLE
Criteria link not working

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/badger-xblock#12]
When trying to open the 'Criterial' link for a badge, the user gets an 'ERR_CONNECTION_TIMED_OUT' error message.

The issue is that when the 'Criteria' is created, the internal mechanism for badgr generates a HTTPS link and is sohuld be a std HTTP url

Steps:
1.  Login to badgr - http://badgr.proversity.org
2.  Click on Issue Badges.
3.  Select a 'Issuer' (Client)
4.  Select a badge.
5.  Click on the 'Criteria' link 

Results.
The user gets an error - See screenshot below
![image](https://user-images.githubusercontent.com/31007393/34662214-9649ef32-f457-11e7-9bce-b1b2bec0f340.png)

Expected results
The user is able to view the criteria of the badge.

**Comment by nicovanniekerk** [comment]
for badgr all urls must be configured to start as HTTP and not HTTPS

**Comment by nicovanniekerk** [comment]
not a bug. config issue

**Comment by nicovanniekerk** [comment]
@mariushuman bug fixed, was in effect a config issue, i opened badgr up to https and it resolved all the problems. please check it out and close when good.

**Comment by mariushuman** [comment]
@nicovanniekerk awesome, all looks good. Badges are showing and the 'Criteria' page loads.
Will close the ticket.
