### ISSUE TITLE
Translations break when badge is loaded

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/badger-xblock#13]
When a course is translated, and badgr is setup to use the translations, it breaks.

Setup Studio
url:  http://staging.studio.proversity.io/course/course-v1:KHD+KHD001AR+2017
**Steps:**
1.  Login to studio 
2.  Select the  KHDA Holacracy® 101 (Arabic) course
3.  Rename/change Module 01 to   الوحدة 01 
4.  Expand module 01
5.  Click on 'Unit 2 Results screen'
6.  Click Edit 
7.  Rename/change the 'Section title' so it is the same as above
8.  Click Save 
9.  Click Publish 

Test on LMS
url:  http://staging.khda.proversity.io/courses/course-v1:KHD+KHD001AR+2017/courseware/320bbb9479ae466faf166d255b636530/59fccce05b9c44379fd5c1436d13d4c1/?activate_block_id=block-v1%3AKHD%2BKHD001AR%2B2017%2Btype%40sequential%2Bblock%4059fccce05b9c44379fd5c1436d13d4c1
**Steps**. 
1.  Click on the link above and login
2.  Select the Welcome to Holacracy® 101 (Arabic) course
3.  Click on the course tab and select the Module 1: Living Holacracy® section and the Module 01 Subsectio
4.  Complete the answer.
5.  Click Next
6.  Click 'Click here to view your results'

**Results**
The mouse cursor turns into an infinity spin wheel 

**Expected results**
The badge should load

**Comment by mariushuman** [comment]
@lidijarad I have tested the badges on staging khda (Welcome to Holacracy 101 (English)) and still get the infinity wheel with the following popup message:
![image](https://user-images.githubusercontent.com/31007393/35610613-a3994140-066a-11e8-8770-233e4e29f259.png)

CC: @nicovanniekerk

**Comment by nicovanniekerk** [comment]
@mariushuman this was due to the badge button being clicked on studio, which will not work. @lidijarad an enhanement here could be to just gooi a popup message in studio, when users accesses something studio can not access.
