### ISSUE TITLE
The tab for badgr text and back ground colour is the same.

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/badger-xblock#16]
When the user get to the page to view his badge, the button text and back ground colour are the same, so the learner won't know he should click on the botton.

url: https://khda.proversity.org/courses/course-v1:KHD+KHD001+2017

Steps
1.  click on the url above and login
2.  If not, complete the course so you can earn your badge, if you already have a badge, go to the badge  section and reset your badge by clicking 'Staff Debug Info', reset your you badge and refresh the page

Results:
The text an the icon colour are the same

Expected Results:
The text should be a different colour to the background colour so the user can read the text.
![image](https://user-images.githubusercontent.com/31007393/36848260-6bf4d306-1d69-11e8-9328-aeb1b400fbd2.png)

**Comment by lidijarad** [comment]
@mariushuman @nicovanniekerk this has been fixed. Closing this issue.
